###
GET http://localhost:5000

###
POST http://localhost:5000/api/crear
Content-Type: application/json

{
    "name": "laptop",
    "price": "1400000",
    "category": "Computing",
    "brand": "coco",
    "available": true
}

###
GET http://localhost:5000/api/listar

###
GET http://localhost:5000/api/listarUno/607635964cb9d01f18eb4f67

###
PUT http://localhost:5000/api/actualizar/6075051e2e33bd033c88930a
Content-Type: application/json

{
    "brand": "pollito"
}

###
DELETE http://localhost:5000/api/eliminar/607635964cb9d01f18eb4f67