###
GET http://localhost:5000

###
POST http://localhost:5000/api/crear
Content-Type: application/json

{
    "name": "laptop",
    "price": "1400000",
    "category": "Computing",
    "brand": "Asus",
    "available": true
}